[package]
name = "api_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
actix-cors = "0.7.1"
actix-files = "0.6"
serde = "1.0.228"
serde_json = "1.0.145"
chrono = "0.4.42"
ureq = "3.1.4"
actix-multipart = "0.7.2"
futures = "0.3.31"
fs2 = "0.4.3"
